// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtevhtJKgmXPIoodpvwBnAwCM6i9_mBuc',
    appId: '1:491697221494:web:941b2f4bd9858f0fd65457',
    messagingSenderId: '491697221494',
    projectId: 'laporpak-fbfc5',
    authDomain: 'laporpak-fbfc5.firebaseapp.com',
    storageBucket: 'laporpak-fbfc5.appspot.com',
    measurementId: 'G-ZJVTHG66XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAaM7Hv73jSAjXQLNZRaK7Yu9ShGsoqQ',
    appId: '1:491697221494:android:951139bfc57c0bdcd65457',
    messagingSenderId: '491697221494',
    projectId: 'laporpak-fbfc5',
    storageBucket: 'laporpak-fbfc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-XlQrdZji43a_NkFd6ruoC4-sZKAOm8',
    appId: '1:491697221494:ios:2332c3ca00ad7710d65457',
    messagingSenderId: '491697221494',
    projectId: 'laporpak-fbfc5',
    storageBucket: 'laporpak-fbfc5.appspot.com',
    iosBundleId: 'com.dytech.laporPak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtevhtJKgmXPIoodpvwBnAwCM6i9_mBuc',
    appId: '1:491697221494:web:ab0acb60a42528a2d65457',
    messagingSenderId: '491697221494',
    projectId: 'laporpak-fbfc5',
    authDomain: 'laporpak-fbfc5.firebaseapp.com',
    storageBucket: 'laporpak-fbfc5.appspot.com',
    measurementId: 'G-KRCYEZRD9H',
  );
}
